version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - env/.env.dev

  db:
    image: postgres
    env_file:
      - env/.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready
      interval: 1s
      timeout: 1s
      retries: 3

volumes:
  pgdata:
