version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      PGUSER: $POSTGRES_USER
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready
      interval: 1s
      timeout: 1s
      retries: 3

volumes:
  pgdata:
